import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// src/app/layout.js o src/app/layout.tsx

import { alfaSlabOne } from '@/app/components/utils/fonts'; // Adjust path as needed



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${openSans.className} ${geistSans.className} ${geistMono.className} ${alfaSlabOne.className}  antialiased`}
      className={`${alfaSlabOne.className} antialiased`}
      >

          {/* // className={` antialiased`}
          > */}

        {children}
      </body>
    </html>
  );
}
