import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// src/app/layout.js o src/app/layout.tsx
import { Alfa_Slab_One } from 'next/font/google'

const alfaSlabOne = Alfa_Slab_One({ subsets: ['latin'], weight: '400' })




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alfaSlabOne.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
